apiVersion: v1
kind: Service
metadata:
  name: python-test-project-service
spec:
  selector:
    app: python_test_project
  ports:
  - protocol: "TCP"
    port: 6000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-test-project
spec:
  selector:
    matchLabels:
      app: python_test_project
  replicas: 1
  template:
    metadata:
      labels:
        app: python_test_project
    spec:
      containers:
      - name: python-test-project
        image: python_test_project:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000